POST http://localhost:7870/register HTTP/1.1
Content-Type: application/json

{
    "username": "demo",
    "password": "demo",
    "email": "demo@demo.com",
    "name": "demo"
}

###

POST http://localhost:7870/login HTTP/1.1
Content-Type: application/json

{
    "password": "demo",
    "email": "demo@demo.com"
}
###

GET http://localhost:7870/get_user_and_profile HTTP/1.1
Content-Type: application/json

{
    "token": "904e16af7046e71efec905b4f77c6eaa8ae91f38e7e5d46b1185b62b124e6ce0"
}