POST http://localhost:7870/register HTTP/1.1
Content-Type: application/json

{
    "username": "demo1",
    "password": "demo1",
    "email": "demo@demo1.com",
    "name": "demo1"
}

###

POST http://localhost:7870/login HTTP/1.1
Content-Type: application/json

{
    "password": "demo1",
    "email": "demo@demo1.com"
}
###

GET http://localhost:7870/get_user_and_profile HTTP/1.1
Content-Type: application/json

{
    "token": "4963d85c0b3e24558ab8a68e287183bb8f68aff9adf029f9cbb059d646cd1129"
}

###
PUT http://localhost:7870/update_user_profile HTTP/1.1
Content-Type: application/json

{
  "token": "ebbc9012b2d6c4d057aea1a396a3aac6982978793342481413870671c8beb564",
  "bio": "Learning full-stack development.",
  "currentPost": "Student",
  "pastWork": [
    {
      "company": "Freelancer",
      "position": "Web Developer",
      "years": "2023"
    }
  ],
  "education": [
    {
      "school": "Government College",
      "degree": "B.Sc",
      "fieldOfStudy": "IT"
    }
  ]
}


###
GET http://localhost:7870/user/get_all_user HTTP/1.1
Content-Type: application/json

