import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useRouter } from "next/navigation";
import UserLayout from "@/layout/userLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  const router = useRouter();
  return (
    <UserLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <div className={styles.container}>
            <div className={styles.mainContainer}>
              <div className={styles.mainContainer_left}>
                <p className={styles.mainContainer_left_header}>
                  Connect with friends without exaggeration.
                </p>
                <p style={{ fontSize: "1.6rem", color: "#4d4d4d" }}>
                  A true social media platform, with stories no blufs!
                </p>
                <div
                  onClick={() => {
                    router.push("/register");
                  }}
                  className={styles.buttonJoin}
                >
                  <p>Join Now</p>
                </div>
              </div>
              <div className={styles.mainContainer_right}>
                <img src="images/homemain_connection.svg" alt="" />
              </div>
            </div>
          </div>
        </main>
      </div>
    </UserLayout>
  );
}
