import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useRouter } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <h2>Hello</h2>
          <div className={styles.container}>
            <div className="mainContainer">
              <div className="mainContainer-left">
                <p>Connect with friends without exaggeration</p>
                <p>A true social media platform, eith stories no blufs!</p>
                <div
                  onClick={() => {
                    router.push("/login");
                  }}
                  className="buttonJoin"
                >
                  <p>Join Now</p>
                </div>
              </div>
              <div className="mainContainer-right">
                <img src="images/homemain_connection.svg" alt="" />
              </div>
            </div>
          </div>
        </main>
      </div>
    </>
  );
}
